pages:
  stage: deploy
  image: alpine:latest

  script:
    - echo "Preparando deploy de frontend"
    - mkdir public
    - cp -r Proyecto_Estancia_La_Granadilla/frontend/* public/

  artifacts:
    paths:
      - public

  only:
    - main